### ISSUE TITLE
Supporting Parcel v2

### ISSUE THREAD

**Issue by nstansbury** [shoonia/parcel-plugin-css-to-string#12]
Is there a config to this working on Parcel v2?

**Comment by shoonia** [comment]
Not yet. The Parcel v2 still in the beta (more than 2 years).

**Comment by shoonia** [comment]
New plugin (transformer) with support Parcel v2. 
https://github.com/shoonia/parcel-transformer-css-to-string

I had to change the plugin name. It requirement in the new plugin API in Parcel v2: 
https://v2.parceljs.org/plugin-system/authoring-plugins/#naming
